import ExcelJS from "exceljs";
import { sanitizeFormulaCell } from "@/lib/csv-safety";
import type { ReportData } from "./types";

export type ColumnFormat = "text" | "integer" | "currency" | "date" | "datetime" | "percent" | "hours";

export interface ReportColumn<Row> {
  header: string;
  format: ColumnFormat;
  width?: number;
  getValue: (row: Row) => unknown;
}

const NUMBER_FORMATS: Record<ColumnFormat, string | undefined> = {
  text: undefined,
  integer: "0",
  currency: '"$"#,##0.00',
  date: "yyyy-mm-dd",
  datetime: "yyyy-mm-dd hh:mm",
  percent: "0%",
  hours: "0.00",
};

function cellValue(format: ColumnFormat, raw: unknown): string | number | Date | null {
  if (raw === null || raw === undefined) return format === "text" ? "" : null;
  if (format === "hours") return typeof raw === "number" ? Math.round((raw / 60) * 100) / 100 : null;
  if (format === "currency") return typeof raw === "number" ? raw / 100 : null;
  if (format === "percent") return typeof raw === "number" ? raw / 100 : null;
  if (format === "date" || format === "datetime") return raw instanceof Date ? raw : null;
  if (format === "integer") return typeof raw === "number" ? raw : null;
  return sanitizeFormulaCell(raw);
}

function styleHeaderRow(row: ExcelJS.Row) {
  row.font = { bold: true };
  row.alignment = { vertical: "middle", wrapText: true };
  row.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE2E8F0" } };
  });
}

/**
 * The one shared workbook builder every report in this program uses — real
 * .xlsx via exceljs (never a renamed CSV, spec §13), always built from the
 * SAME ReportData the on-screen API returns, so totals can never diverge
 * (spec §14). Three worksheets: Report Information, Summary, Detailed Data.
 */
export async function buildVolunteerReportWorkbook<Row>(
  data: ReportData<Row>,
  columns: ReportColumn<Row>[]
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Unestra";
  workbook.created = data.info.generatedAt;

  // ── Report Information ──────────────────────────────────────────────
  const infoSheet = workbook.addWorksheet("Report Information");
  infoSheet.columns = [
    { header: "Field", key: "field", width: 28 },
    { header: "Value", key: "value", width: 70 },
  ];
  styleHeaderRow(infoSheet.getRow(1));
  infoSheet.views = [{ state: "frozen", ySplit: 1 }];
  const infoRows: [string, string][] = [
    ["Organization", data.info.organizationName],
    ["Report title", data.info.reportTitle],
    ["Requirement period", data.info.requirementPeriodName],
    ["Covered date range", data.info.coveredDateRange],
    ["Organization time zone", data.info.organizationTimezone],
    ["Generated at", data.info.generatedAt.toISOString()],
    ["Generated by", data.info.generatedByName],
  ];
  for (const [field, value] of infoRows) {
    infoSheet.addRow({ field, value: sanitizeFormulaCell(value) });
  }
  if (Object.keys(data.info.appliedFilters).length > 0) {
    infoSheet.addRow({ field: "", value: "" });
    infoSheet.addRow({ field: "Applied filters", value: "" }).font = { bold: true };
    for (const [key, value] of Object.entries(data.info.appliedFilters)) {
      infoSheet.addRow({ field: key, value: sanitizeFormulaCell(value) });
    }
  }
  if (data.info.calculationNotes.length > 0) {
    infoSheet.addRow({ field: "", value: "" });
    infoSheet.addRow({ field: "Calculation notes", value: "" }).font = { bold: true };
    for (const note of data.info.calculationNotes) {
      infoSheet.addRow({ field: "", value: sanitizeFormulaCell(note) }).alignment = { wrapText: true };
    }
  }

  // ── Summary ──────────────────────────────────────────────────────────
  const summarySheet = workbook.addWorksheet("Summary");
  summarySheet.columns = [
    { header: "Metric", key: "metric", width: 36 },
    { header: "Value", key: "value", width: 20 },
  ];
  styleHeaderRow(summarySheet.getRow(1));
  summarySheet.views = [{ state: "frozen", ySplit: 1 }];
  const s = data.summary;
  // fix/pta-volunteer-financial-controls: `undefined` (not 0) means the
  // caller was never given this figure to begin with (see
  // ReportSummaryTotals's doc comment) — the Summary sheet must omit the
  // row entirely, not show a misleading "$0.00" a non-financial viewer could
  // misread as "no balance."
  const summaryRows: [string, number | undefined, ColumnFormat][] = [
    ["Total families", s.totalFamilies, "integer"],
    ["Total individual volunteers", s.totalIndividualVolunteers, "integer"],
    ["Total verified volunteer hours", s.totalVerifiedMinutes, "hours"],
    ["Total event volunteer hours", s.totalEventMinutes, "hours"],
    ["Total non-event volunteer hours", s.totalNonEventMinutes, "hours"],
    ["Total pending hours", s.totalPendingMinutes, "hours"],
    ["Total purchased hours", s.totalPurchasedMinutes, "hours"],
    ["Total waived hours", s.totalWaivedMinutes, "hours"],
    ["Total remaining required hours", s.totalRemainingMinutes, "hours"],
    ["Families meeting requirement", s.familiesMeetingRequirement, "integer"],
    ["Families not meeting requirement", s.familiesNotMeetingRequirement, "integer"],
    ["Families exempt", s.familiesExempt, "integer"],
    ["Total buyout revenue", s.totalBuyoutRevenueCents, "currency"],
    ["Total assessments", s.totalAssessmentsCents, "currency"],
    ["Outstanding balance", s.outstandingBalanceCents, "currency"],
  ];
  for (const [metric, value, format] of summaryRows) {
    if (value === undefined) continue;
    const row = summarySheet.addRow({ metric, value: cellValue(format, value) });
    const numFmt = NUMBER_FORMATS[format];
    if (numFmt) row.getCell("value").numFmt = numFmt;
  }

  // ── Detailed Data ────────────────────────────────────────────────────
  const detailSheet = workbook.addWorksheet("Detailed Data");
  detailSheet.columns = columns.map((col) => ({ header: col.header, key: col.header, width: col.width ?? 18 }));
  styleHeaderRow(detailSheet.getRow(1));
  detailSheet.views = [{ state: "frozen", ySplit: 1 }];
  detailSheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: columns.length } };

  for (const row of data.rows) {
    const values: Record<string, unknown> = {};
    for (const col of columns) {
      values[col.header] = cellValue(col.format, col.getValue(row));
    }
    detailSheet.addRow(values);
  }
  columns.forEach((col, i) => {
    const numFmt = NUMBER_FORMATS[col.format];
    if (numFmt) {
      const column = detailSheet.getColumn(i + 1);
      column.numFmt = numFmt;
    }
  });

  // Total row for numeric columns (spec §13 "total rows"), values only —
  // exported workbooks stay accurate without relying on formula support in
  // whatever spreadsheet application opens them (spec §13).
  const totalsRow: Record<string, unknown> = {};
  let hasTotals = false;
  columns.forEach((col) => {
    if (col.format === "hours" || col.format === "currency" || col.format === "integer") {
      const sum = data.rows.reduce((acc, row) => {
        const raw = col.getValue(row);
        return acc + (typeof raw === "number" ? raw : 0);
      }, 0);
      totalsRow[col.header] = cellValue(col.format, sum);
      hasTotals = true;
    } else if (col === columns[0]) {
      totalsRow[col.header] = "Total";
    }
  });
  if (hasTotals && data.rows.length > 0) {
    const row = detailSheet.addRow(totalsRow);
    row.font = { bold: true };
  }

  const arrayBuffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer);
}

export function sanitizeFilenameSegment(input: string): string {
  return input
    .normalize("NFKD")
    .replace(/[^\w\- ]+/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 80);
}

export function buildReportFilename(organizationName: string, reportTitle: string, requirementPeriodName: string): string {
  const org = sanitizeFilenameSegment(organizationName);
  const title = sanitizeFilenameSegment(reportTitle);
  const period = sanitizeFilenameSegment(requirementPeriodName);
  const date = new Date().toISOString().slice(0, 10);
  return `${org}_${title}_${period}_${date}.xlsx`;
}
