import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { prisma } from "@/lib/prisma";
import { createAuditEvent } from "@/lib/audit";
import { formatCurrency } from "@/lib/formatting";
import { paymentMethodLabels } from "@/lib/payment-methods";
import { buildSafeObjectKey, uploadBufferToSpaces } from "@/lib/storage";

type ReceiptPayload = {
  organizationName: string;
  organizationAddressLines: string[];
  organizationContactLine: string | null;
  memberName?: string;
  amount: string;
  date: string;
  receiptNumber: string;
  paymentMethod?: string;
};

function organizationAddressLines(org: {
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  state: string | null;
  zipCode: string | null;
}): string[] {
  const lines: string[] = [];
  if (org.addressLine1) lines.push(org.addressLine1);
  if (org.addressLine2) lines.push(org.addressLine2);
  const cityStateZip = [org.city, [org.state, org.zipCode].filter(Boolean).join(" ")].filter(Boolean).join(", ");
  if (cityStateZip) lines.push(cityStateZip);
  return lines;
}

/**
 * Renders a single-page receipt PDF with pdf-lib, mirroring the layout
 * conventions already established in src/lib/reports/exporters.ts
 * (exportReportPdf) — same font/color choices, same "draw text at explicit
 * x/y" approach — rather than introducing a second PDF-generation style.
 * Previously this produced a plain-text buffer saved with a .txt extension
 * despite the function name and surrounding UI implying a real PDF
 * artifact; that was a stub masquerading as a finished feature.
 */
async function renderReceiptPdf(payload: ReceiptPayload): Promise<Buffer> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const pageWidth = 612;
  const pageHeight = 792;
  const margin = 56;
  const page = pdf.addPage([pageWidth, pageHeight]);

  let y = pageHeight - margin;

  page.drawText(payload.organizationName, { x: margin, y, size: 18, font: bold, color: rgb(0.02, 0.09, 0.18) });
  y -= 22;

  for (const line of payload.organizationAddressLines) {
    page.drawText(line, { x: margin, y, size: 9, font: regular, color: rgb(0.35, 0.4, 0.48) });
    y -= 13;
  }
  if (payload.organizationContactLine) {
    page.drawText(payload.organizationContactLine, { x: margin, y, size: 9, font: regular, color: rgb(0.35, 0.4, 0.48) });
    y -= 13;
  }

  y -= 24;
  page.drawText("Payment Receipt", { x: margin, y, size: 15, font: bold, color: rgb(0.02, 0.09, 0.18) });
  y -= 8;
  page.drawLine({
    start: { x: margin, y },
    end: { x: pageWidth - margin, y },
    thickness: 1,
    color: rgb(0.85, 0.87, 0.9),
  });
  y -= 28;

  const rows: [string, string][] = [
    ["Receipt Number", payload.receiptNumber],
    ["Date", payload.date],
    ["Amount", payload.amount],
    ["Received From", payload.memberName ?? "N/A"],
    ["Payment Method", payload.paymentMethod ?? "N/A"],
  ];

  for (const [label, value] of rows) {
    page.drawText(label, { x: margin, y, size: 10, font: bold, color: rgb(0.28, 0.33, 0.41) });
    page.drawText(value, { x: margin + 160, y, size: 10, font: regular, color: rgb(0.08, 0.11, 0.17) });
    y -= 20;
  }

  y -= 20;
  page.drawText(`Thank you for your support of ${payload.organizationName}.`, {
    x: margin,
    y,
    size: 9,
    font: regular,
    color: rgb(0.35, 0.4, 0.48),
  });
  y -= 13;
  page.drawText("This receipt was generated by Unestra and reflects the information on file at the time of generation.", {
    x: margin,
    y,
    size: 8,
    font: regular,
    color: rgb(0.45, 0.5, 0.57),
  });

  return Buffer.from(await pdf.save());
}

export async function generateAndStoreReceiptPdf(params: {
  organizationId: string;
  actorUserId?: string;
  actorEmail?: string;
  receiptId: string;
}) {
  const receipt = await prisma.contributionReceipt.findFirst({
    where: { id: params.receiptId, organizationId: params.organizationId },
    include: {
      organization: true,
      contribution: true,
      member: true,
    },
  });

  if (!receipt) {
    throw new Error("Receipt not found");
  }

  const methodConfig = receipt.contribution.paymentMethod
    ? await prisma.paymentMethodConfig.findFirst({
        where: {
          organizationId: params.organizationId,
          method: receipt.contribution.paymentMethod,
        },
        select: { label: true },
      })
    : null;

  const contactParts = [receipt.organization.email, receipt.organization.phone].filter(Boolean);

  const payload: ReceiptPayload = {
    organizationName: receipt.organization.name,
    organizationAddressLines: organizationAddressLines(receipt.organization),
    organizationContactLine: contactParts.length ? contactParts.join(" · ") : null,
    memberName: receipt.member
      ? `${receipt.member.firstName} ${receipt.member.lastName}`
      : undefined,
    amount: formatCurrency(receipt.contribution.amount),
    date: receipt.contribution.contributionDate.toISOString().slice(0, 10),
    receiptNumber: receipt.receiptNumber,
    paymentMethod: receipt.contribution.paymentMethod
      ? methodConfig?.label ??
        paymentMethodLabels.get(receipt.contribution.paymentMethod) ??
        receipt.contribution.paymentMethod
      : "N/A",
  };

  const receiptBuffer = await renderReceiptPdf(payload);
  const objectKey = buildSafeObjectKey(
    `receipts/${params.organizationId}`,
    `${payload.receiptNumber}.pdf`
  );

  await uploadBufferToSpaces({
    key: objectKey,
    buffer: receiptBuffer,
    contentType: "application/pdf",
    metadata: {
      receiptId: receipt.id,
      organizationId: params.organizationId,
    },
  });

  const metadata = {
    ...(typeof receipt.metadata === "object" && receipt.metadata ? receipt.metadata : {}),
    fileKey: objectKey,
    fileType: "application/pdf",
    generatedAt: new Date().toISOString(),
    format: "PDF_RECEIPT",
  };

  const updated = await prisma.contributionReceipt.update({
    where: { id: receipt.id },
    data: {
      deliveryStatus: "SENT",
      deliveredAt: new Date(),
      metadata,
    },
  });

  await prisma.attachment.create({
    data: {
      organizationId: params.organizationId,
      entityType: "RECEIPT",
      entityId: receipt.id,
      purpose: "RECEIPT_FILE",
      fileName: `${payload.receiptNumber}.pdf`,
      contentType: "application/pdf",
      byteSize: receiptBuffer.byteLength,
      objectKey,
      title: `Receipt ${payload.receiptNumber}`,
      uploadedByUserId: params.actorUserId,
    },
  });

  await createAuditEvent({
    organizationId: params.organizationId,
    actorUserId: params.actorUserId,
    actorEmail: params.actorEmail,
    action: "receipt",
    entityType: "contribution_receipt",
    entityId: updated.id,
    metadata: {
      event: "pdf_generated",
      fileKey: objectKey,
      receiptNumber: updated.receiptNumber,
    },
  });

  return {
    receipt: updated,
    fileKey: objectKey,
  };
}
