import { prisma } from "@/lib/prisma";
import { createAuditEvent } from "@/lib/audit";
import { paymentMethodLabels } from "@/lib/payment-methods";
import { buildSafeObjectKey, uploadBufferToSpaces } from "@/lib/storage";

type ReceiptPayload = {
  organizationName: string;
  memberName?: string;
  amount: string;
  date: string;
  receiptNumber: string;
  paymentMethod?: string;
};

function renderReceiptBuffer(payload: ReceiptPayload): Buffer {
  const lines = [
    "CivicFlow Receipt",
    "================",
    `Organization: ${payload.organizationName}`,
    `Receipt Number: ${payload.receiptNumber}`,
    `Date: ${payload.date}`,
    `Amount: ${payload.amount}`,
    `Member: ${payload.memberName ?? "N/A"}`,
    `Payment Method: ${payload.paymentMethod ?? "N/A"}`,
    "",
    "Generated by CivicFlow SaaS.",
    "This receipt artifact can be stored, delivered, and referenced from the portal.",
  ];
  return Buffer.from(lines.join("\n"), "utf8");
}

export async function generateAndStoreReceiptPdf(params: {
  organizationId: string;
  actorUserId?: string;
  actorEmail?: string;
  receiptId: string;
}) {
  const receipt = await prisma.contributionReceipt.findFirst({
    where: { id: params.receiptId, organizationId: params.organizationId },
    include: {
      organization: true,
      contribution: true,
      member: true,
    },
  });

  if (!receipt) {
    throw new Error("Receipt not found");
  }

  const methodConfig = receipt.contribution.paymentMethod
    ? await prisma.paymentMethodConfig.findFirst({
        where: {
          organizationId: params.organizationId,
          method: receipt.contribution.paymentMethod,
        },
        select: { label: true },
      })
    : null;

  const payload: ReceiptPayload = {
    organizationName: receipt.organization.name,
    memberName: receipt.member
      ? `${receipt.member.firstName} ${receipt.member.lastName}`
      : undefined,
    amount: receipt.contribution.amount.toString(),
    date: receipt.contribution.contributionDate.toISOString().slice(0, 10),
    receiptNumber: receipt.receiptNumber,
    paymentMethod: receipt.contribution.paymentMethod
      ? methodConfig?.label ??
        paymentMethodLabels.get(receipt.contribution.paymentMethod) ??
        receipt.contribution.paymentMethod
      : "N/A",
  };

  const receiptBuffer = renderReceiptBuffer(payload);
  const objectKey = buildSafeObjectKey(
    `receipts/${params.organizationId}`,
    `${payload.receiptNumber}.txt`
  );

  await uploadBufferToSpaces({
    key: objectKey,
    buffer: receiptBuffer,
    contentType: "text/plain",
    metadata: {
      receiptId: receipt.id,
      organizationId: params.organizationId,
    },
  });

  const metadata = {
    ...(typeof receipt.metadata === "object" && receipt.metadata ? receipt.metadata : {}),
    fileKey: objectKey,
    fileType: "text/plain",
    generatedAt: new Date().toISOString(),
    format: "TEXT_RECEIPT",
  };

  const updated = await prisma.contributionReceipt.update({
    where: { id: receipt.id },
    data: {
      deliveryStatus: "SENT",
      deliveredAt: new Date(),
      metadata,
    },
  });

  await prisma.attachment.create({
    data: {
      organizationId: params.organizationId,
      entityType: "RECEIPT",
      entityId: receipt.id,
      purpose: "RECEIPT_FILE",
      fileName: `${payload.receiptNumber}.txt`,
      contentType: "text/plain",
      byteSize: receiptBuffer.byteLength,
      objectKey,
      title: `Receipt ${payload.receiptNumber}`,
      uploadedByUserId: params.actorUserId,
    },
  });

  await createAuditEvent({
    organizationId: params.organizationId,
    actorUserId: params.actorUserId,
    actorEmail: params.actorEmail,
    action: "receipt",
    entityType: "contribution_receipt",
    entityId: updated.id,
    metadata: {
      event: "pdf_generated",
      fileKey: objectKey,
      receiptNumber: updated.receiptNumber,
    },
  });

  return {
    receipt: updated,
    fileKey: objectKey,
  };
}
