<#
.SYNOPSIS
  One-time Windows dev environment setup for Unestra: installs dependencies,
  provisions a genuinely LOCAL PostgreSQL database for civicflow-portal (never
  touching production), and seeds it with fictional demo data.

.PARAMETER PgUser
  Local PostgreSQL superuser to connect as. Default: postgres

.PARAMETER PgPassword
  Password for -PgUser. If omitted, you'll be prompted (not echoed).

.PARAMETER PgHost
  Local PostgreSQL host. Default: localhost. Must resolve to localhost/127.0.0.1 —
  this script refuses to run against anything else.

.PARAMETER PgPort
  Local PostgreSQL port. Default: 5432

.PARAMETER SkipSeed
  Skip the fictional demo-data seed step (schema/migrations still run).
#>
param(
    [string]$PgUser = "postgres",
    [SecureString]$PgPassword,
    [string]$PgHost = "localhost",
    [int]$PgPort = 5432,
    [switch]$SkipSeed
)

. "$PSScriptRoot\common.ps1"

if ($PgHost -notin @('localhost', '127.0.0.1')) {
    Write-Fail "PgHost must be localhost or 127.0.0.1 -- this script only ever provisions a local dev database."
    exit 1
}

Write-Step "Checking prerequisites"
$node = Assert-Command -Name "node" -InstallHint "Install Node.js from https://nodejs.org/"
$nodeVersion = (& node --version).Trim()
Write-Ok "node $nodeVersion (developed/verified against v24.x; no strict engines pin exists in this repo yet)"
Assert-Command -Name "npm" | Out-Null
Write-Ok "npm $((& npm --version).Trim())"
$psql = Assert-Command -Name "psql" -InstallHint "Install PostgreSQL (e.g. from https://www.postgresql.org/download/windows/) and ensure its bin\ directory is on PATH."
Write-Ok "psql found at $($psql.Source)"

if (-not $PgPassword) {
    $PgPassword = Read-Host -Prompt "Local PostgreSQL password for user '$PgUser'" -AsSecureString
}
$bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($PgPassword)
$plainPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
[System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
$env:PGPASSWORD = $plainPassword

Write-Step "Testing local PostgreSQL connection"
& psql -U $PgUser -h $PgHost -p $PgPort -d postgres -c "SELECT 1;" *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Fail "Could not connect to PostgreSQL at $($PgHost):$($PgPort) as '$PgUser'."
    Write-Fail "Check the password and that the PostgreSQL service is running (services.msc -> postgresql-x64-*)."
    exit 1
}
Write-Ok "Connected to local PostgreSQL as $PgUser@$($PgHost):$PgPort"

Write-Step "Creating local dev database 'civicflow_dev' (if it doesn't already exist)"
$dbExists = & psql -U $PgUser -h $PgHost -p $PgPort -d postgres -t -c "SELECT 1 FROM pg_database WHERE datname = 'civicflow_dev';"
if ($dbExists -match '1') {
    Write-Ok "civicflow_dev already exists -- leaving it as-is."
} else {
    & psql -U $PgUser -h $PgHost -p $PgPort -d postgres -c "CREATE DATABASE civicflow_dev;" | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Fail "Failed to create civicflow_dev."
        exit 1
    }
    Write-Ok "Created civicflow_dev."
}

$localDatabaseUrl = "postgresql://${PgUser}:${plainPassword}@${PgHost}:${PgPort}/civicflow_dev?schema=public"

Write-Step "Writing civicflow-portal\.env.development.local (never touches .env.local)"
$envDevLocalPath = Join-Path $RepoRoot "civicflow-portal\.env.development.local"
if (Test-Path $envDevLocalPath) {
    Write-Warn ".env.development.local already exists -- leaving it untouched. Delete it first if you want this script to regenerate it."
} else {
    $secret = [Convert]::ToBase64String((1..48 | ForEach-Object { Get-Random -Maximum 256 }))
    @"
# Generated by scripts\windows\setup-dev.ps1 -- local development only.
# This file takes precedence over .env.local when NODE_ENV=development
# (Next.js env-loading order: .env.development.local > .env.local > .env),
# so it safely overrides whatever .env.local points at (which may be
# production) without deleting or modifying that file.
DATABASE_URL="$localDatabaseUrl"
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=$secret
ENABLE_EMAIL_SEND=0
"@ | Set-Content -Path $envDevLocalPath -Encoding utf8
    Write-Ok "Wrote civicflow-portal\.env.development.local"
}

Write-Step "Installing dependencies"
foreach ($dir in @("civicflow-portal", "civicflow-mobile", "cloud-api", "civicflow-license-server", ".")) {
    $full = Join-Path $RepoRoot $dir
    Write-Host "  npm install in $dir ..."
    Push-Location $full
    try {
        & npm install --no-audit --no-fund
        if ($LASTEXITCODE -ne 0) { Write-Fail "npm install failed in $dir"; exit 1 }
    } finally {
        Pop-Location
    }
}
Write-Ok "Dependencies installed."

Write-Step "Running Prisma migrations against the local dev database"
Push-Location (Join-Path $RepoRoot "civicflow-portal")
try {
    $env:DATABASE_URL = $localDatabaseUrl
    & npx prisma generate
    if ($LASTEXITCODE -ne 0) { Write-Fail "prisma generate failed"; exit 1 }
    & npx prisma migrate deploy
    if ($LASTEXITCODE -ne 0) { Write-Fail "prisma migrate deploy failed"; exit 1 }
    Write-Ok "Schema is up to date on civicflow_dev."

    if (-not $SkipSeed) {
        Write-Step "Seeding fictional demo data (Pine Grove PTA, Riverdale, etc.)"
        & npm run db:seed
        & npm run db:seed:pta-demo
        Write-Ok "Seed data loaded."
    } else {
        Write-Warn "Skipped seeding (-SkipSeed)."
    }
} finally {
    Remove-Item Env:\DATABASE_URL -ErrorAction SilentlyContinue
    Pop-Location
}

Write-Step "Done"
Write-Host "  Local dev database: civicflow_dev on $($PgHost):$PgPort"
Write-Host "  civicflow-portal:   scripts\windows\start-portal.ps1"
Write-Host "  civicflow-mobile:   scripts\windows\start-mobile.ps1"
Write-Host "  Electron desktop:   scripts\windows\start-desktop.ps1"
Write-Host "  Everything at once: scripts\windows\start-all.ps1"
Write-Host ""
Write-Host "  Your existing civicflow-portal\.env.local is untouched. If it points at" -ForegroundColor Yellow
Write-Host "  production, .env.development.local (just created) takes precedence during" -ForegroundColor Yellow
Write-Host "  'npm run dev' so local development no longer touches production." -ForegroundColor Yellow
