<#
.SYNOPSIS
  Starts the Expo dev server for civicflow-mobile, pointed at your locally
  running portal instead of production.

.DESCRIPTION
  civicflow-mobile\.env currently ships with EXPO_PUBLIC_API_BASE_URL pointing
  at the production portal (civicflow-portal-iule6.ondigitalocean.app) -- a
  real "staging silently talks to production" risk. This script creates a
  local-only civicflow-mobile\.env.development.local (which Expo's env loader
  prefers over .env when NODE_ENV=development) pointing at your machine's LAN
  IP instead, so Expo Go on a physical device or the Android emulator can
  actually reach your locally running civicflow-portal.
#>
. "$PSScriptRoot\common.ps1"

$mobileDir = Join-Path $RepoRoot "civicflow-mobile"
$envDevLocalPath = Join-Path $mobileDir ".env.development.local"

if (-not (Test-Path $envDevLocalPath)) {
    $lanIp = (Get-NetIPAddress -AddressFamily IPv4 -PrefixOrigin Dhcp -ErrorAction SilentlyContinue |
        Where-Object { $_.IPAddress -notlike '169.254.*' } |
        Select-Object -First 1 -ExpandProperty IPAddress)
    if (-not $lanIp) {
        $lanIp = "localhost"
        Write-Warn "Could not auto-detect a LAN IP; defaulting to localhost, which only works for the iOS Simulator, not a physical device or Android emulator."
    }

    @"
# Generated by scripts\windows\start-mobile.ps1 -- local development only.
# Takes precedence over the committed .env (which points at production) when
# NODE_ENV=development. Edit the IP below if it's wrong for your network, or
# if you're only ever using the iOS Simulator you can set this to localhost.
EXPO_PUBLIC_API_BASE_URL=http://${lanIp}:3000
"@ | Set-Content -Path $envDevLocalPath -Encoding utf8
    Write-Ok "Wrote civicflow-mobile\.env.development.local pointing at http://${lanIp}:3000"
    Write-Warn "Make sure civicflow-portal is running (scripts\windows\start-portal.ps1) and reachable at that address before testing on a device."
} else {
    Write-Ok "Using existing civicflow-mobile\.env.development.local"
}

Push-Location $mobileDir
try {
    & npm start
} finally {
    Pop-Location
}
