import type { OrganizationVertical } from "@prisma/client";

export type KnowledgeVisibility = "public" | "in_app" | "both";

export type KnowledgeDocument = {
  id: string;
  title: string;
  href: string;
  category:
    | "general"
    | "member-administration"
    | "rosters-reports"
    | "payments-dues"
    | "pta"
    | "union"
    | "hoa"
    | "mobile"
    | "account-security";
  /** OrganizationVertical this content applies to, or "ALL" for vertical-agnostic content. */
  vertical: OrganizationVertical | "ALL";
  /** Who the content is written for -- distinct from `visibility` (which surface may show it). */
  audience: string;
  publicationStatus: "published";
  version: string;
  lastReviewedDate: string;
  /** Which surface may serve this document -- a doc can be accurate but still
   * inappropriate for the anonymous public widget (e.g. specific in-app
   * navigation instructions that assume a logged-in staff session). */
  visibility: KnowledgeVisibility;
  owner: string;
  keywords: string[];
  text: string;
};

// Every entry here describes real, shipped Unestra behavior only -- nothing
// aspirational, nothing pricing-specific (pricing pages change independently
// of this codebase and must never be hardcoded into assistant knowledge).
export const KNOWLEDGE_DOCUMENTS: KnowledgeDocument[] = [
  {
    id: "general-what-is-unestra",
    title: "What is Unestra?",
    href: "/pricing",
    category: "general",
    vertical: "ALL",
    audience: "Anyone evaluating or new to Unestra",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "both",
    owner: "product",
    keywords: ["what is unestra", "about", "product", "overview", "platform"],
    text: "Unestra is a membership and organization-management platform for community organizations, PTA/PTO groups, unions, and HOAs. It handles member records, dues and payments, communications, meetings and attendance, reports, and a mobile app for members and officers. Each organization picks one vertical (Community, PTA, Union, or HOA) that adapts terminology and available workflows to that kind of organization.",
  },
  {
    id: "general-vertical-selection",
    title: "Choosing an organization type (vertical)",
    href: "/onboarding/organization",
    category: "general",
    vertical: "ALL",
    audience: "New organization administrators during signup",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "both",
    owner: "product",
    keywords: ["vertical", "organization type", "community", "pta", "pto", "union", "hoa", "signup", "onboarding"],
    text: "During signup, an organization chooses one primary type: Community Organization (general-purpose membership org), PTA/PTO (school parent-teacher groups, with households and students), Union (dues and payroll checkoff), or HOA (homeowners association, with properties and residents). This choice changes the terminology used throughout the app (for example, HOA calls members 'Residents' and dues 'Assessments') and which features are available. An organization's type can be changed later by contacting support.",
  },
  {
    id: "general-signup",
    title: "Creating an organization",
    href: "/signup",
    category: "general",
    vertical: "ALL",
    audience: "New users",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "both",
    owner: "product",
    keywords: ["signup", "sign up", "create account", "create organization", "get started", "register"],
    text: "New organizations sign up at the Unestra signup page with an email, password, and organization name, then choose their organization type. After signup, an onboarding checklist walks through initial setup like adding members and configuring dues.",
  },
  {
    id: "general-pricing",
    title: "Plans and pricing",
    href: "/pricing",
    category: "general",
    vertical: "ALL",
    audience: "Anyone evaluating Unestra",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "both",
    owner: "product",
    keywords: ["price", "pricing", "plan", "plans", "cost", "how much", "billing", "subscription"],
    text: "Unestra offers multiple plans with different feature sets and limits. Exact current pricing, plan names, and feature comparisons are published on the Pricing page, since they can change -- I don't have a live, guaranteed-current price list to quote from memory. Please check the Pricing page or contact Unestra Support for current plan details.",
  },
  {
    id: "account-password-reset",
    title: "Resetting your password",
    href: "/reset-password",
    category: "account-security",
    vertical: "ALL",
    audience: "Anyone locked out of their account",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "both",
    owner: "product",
    keywords: ["password", "reset password", "forgot password", "locked out", "can't log in", "login help"],
    text: "To reset a forgotten password, use the 'Forgot password?' link on the login page. A password reset email is sent to the account's email address with a link to set a new password. If the email doesn't arrive, check spam/junk folders, confirm the email address on file, and contact Unestra Support if the issue continues.",
  },
  {
    id: "account-mfa",
    title: "Account security and multi-factor authentication",
    href: "/settings/security",
    category: "account-security",
    vertical: "ALL",
    audience: "Any authenticated user",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["mfa", "2fa", "two factor", "multi factor", "security", "authenticator"],
    text: "Unestra supports optional multi-factor authentication (MFA) using an authenticator app, with backup codes and an SMS fallback. MFA can be enabled or managed from Settings → Security.",
  },
  {
    id: "mobile-app-install",
    title: "Installing the Unestra mobile app",
    href: "/settings/organization",
    category: "mobile",
    vertical: "ALL",
    audience: "Members and officers who want mobile access",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "both",
    owner: "product",
    keywords: ["mobile", "app", "install", "download", "phone", "ios", "android"],
    text: "Unestra has a companion mobile app for members and officers to view dues, make payments, receive announcements, and (for HOA) submit violations-related or architectural request information. A member gets mobile access when an officer sends them an app invite from their member profile; the member then sets up a password to log in on their phone.",
  },
  {
    id: "member-admin-lifecycle",
    title: "Member status and lifecycle",
    href: "/members",
    category: "member-administration",
    vertical: "ALL",
    audience: "Organization administrators",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["member status", "active", "inactive", "membership status", "lifecycle"],
    text: "Members have a status such as Active, Pending, Inactive, Deactivated, Retired, Suspended, or Terminated. A member can also be flagged Delinquent independently of status, meaning they have unpaid dues. Status changes (other than termination) are made from a member's Edit Member page.",
  },
  {
    id: "member-admin-termination",
    title: "Terminating a member",
    href: "/members",
    category: "member-administration",
    vertical: "ALL",
    audience: "Organization administrators and owners",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["terminate", "termination", "remove member", "cancel membership", "end membership"],
    text: "To terminate a member, open their profile and use the 'Terminate Membership' button (visible to organization owners and admins). You'll choose a reason (or 'Other' with a description), an effective date, and optional internal notes. Terminating a member also suspends that person's app login access for this organization if they have one linked, and is recorded on the member's timeline. Terminating an organization's only owner-level login is not allowed, to avoid locking the organization out of administration.",
  },
  {
    id: "member-admin-reinstatement",
    title: "Reinstating a terminated member",
    href: "/members",
    category: "member-administration",
    vertical: "ALL",
    audience: "Organization administrators and owners",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["reinstate", "reinstatement", "restore member", "undo termination", "reactivate member"],
    text: "A terminated member can be reinstated from their profile using the 'Reinstate Membership' button, which requires a reason and an effective date and returns their status to Active. Reinstating a member does not automatically restore their app login access -- that must be granted separately from Settings → Users & Roles if they previously had it.",
  },
  {
    id: "rosters-reports-overview",
    title: "Member roster reports",
    href: "/reports",
    category: "rosters-reports",
    vertical: "ALL",
    audience: "Organization administrators",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["roster", "active roster", "delinquent roster", "inactive roster", "terminated roster", "member list report"],
    text: "The Reports page has ready-made Member Roster reports for Active, Delinquent, Inactive, and Terminated members, each exportable as CSV, Excel, or PDF (PDF export requires a plan that includes it). These are found under the 'Member Rosters'/'Rosters' section at the top of the Reports page, with a live count for each and a link straight into a preview.",
  },
  {
    id: "rosters-reports-exports",
    title: "Exporting and emailing reports",
    href: "/reports",
    category: "rosters-reports",
    vertical: "ALL",
    audience: "Organization administrators",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["export report", "download report", "email report", "csv", "excel", "pdf export"],
    text: "Any report on the Reports page can be previewed, then exported as CSV, XLSX, or PDF, or emailed to a chosen recipient group (all active members, a filtered set, or manually selected members). Exporting and sending reports requires the reports:export permission; financial reports (like delinquent-dues reports) additionally require a finance or administrator role.",
  },
  {
    id: "member-profile-overview",
    title: "The member profile page",
    href: "/members",
    category: "rosters-reports",
    vertical: "ALL",
    audience: "Organization administrators",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["member profile", "member page", "member details", "member tabs"],
    text: "A member's profile page is organized into tabs: Overview (contact info, status, timeline), Dues & Payments, Contributions, Communications & Attendance, and Documents. Quick actions like Edit Member, Terminate/Reinstate Membership, and messaging appear at the top, adjusted to what the current user is permitted to do.",
  },
  {
    id: "payments-dues-overview",
    title: "Dues and payments",
    href: "/dues",
    category: "payments-dues",
    vertical: "ALL",
    audience: "Organization administrators and finance officers",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["dues", "payment", "pay", "invoice", "charge", "outstanding balance"],
    text: "Unestra tracks dues charges, payments, and adjustments per member, with outstanding-balance calculation and delinquency flagging based on an organization's configured grace period. Payments can be recorded manually by staff or made online by a member.",
  },
  {
    id: "payments-links",
    title: "Payment links",
    href: "/payment-links",
    category: "payments-dues",
    vertical: "ALL",
    audience: "Organization administrators",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["payment link", "shareable link", "pay link", "checkout link"],
    text: "Payment Links let an organization create a shareable public page for anyone to pay without logging in, for purposes like a fixed dues amount, a general contribution, or a campaign donation. See the Payment Links section for current details on which payment methods a given link supports.",
  },
  {
    id: "pta-households",
    title: "PTA/PTO households and students",
    href: "/labs/pta/households",
    category: "pta",
    vertical: "PTA",
    audience: "PTA/PTO officers",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["household", "student", "pta", "pto", "parent", "family"],
    text: "PTA/PTO organizations track membership by household, with one or more parent/guardian adults and one or more students linked to each household. A household's membership and dues status apply to the whole family group.",
  },
  {
    id: "pta-volunteers-dues-committees",
    title: "PTA/PTO volunteers, dues, and committees",
    href: "/labs/pta/dashboard",
    category: "pta",
    vertical: "PTA",
    audience: "PTA/PTO officers and parent volunteers",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "both",
    owner: "product",
    keywords: ["volunteer", "volunteer hours", "committee", "pta dues", "membership dues"],
    text: "PTA/PTO organizations can track volunteer opportunities and hours, organize committees, and collect membership dues per household. Parents can sign up for volunteer opportunities and log hours through their household's mobile or web access where enabled by the organization.",
  },
  {
    id: "union-dues-checkoff",
    title: "Union dues and payroll checkoff",
    href: "/dues",
    category: "union",
    vertical: "UNION",
    audience: "Union officers",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["union dues", "payroll checkoff", "checkoff", "union payment"],
    text: "Union organizations can track member dues, including dues collected through employer payroll checkoff. Payroll checkoff records in Unestra are administrative -- reflecting amounts an employer has deducted and remitted -- rather than a member-initiated payment inside the app.",
  },
  {
    id: "union-unionflow-boundary",
    title: "Unestra for Unions vs. UnionFlow",
    href: "/dashboard",
    category: "union",
    vertical: "UNION",
    audience: "Union officers",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["unionflow", "union flow", "difference", "which product"],
    text: "Unestra for Unions covers membership, dues, and meeting/attendance tracking. UnionFlow is a related but separate APH Technologies product; if you're asking about a UnionFlow-specific capability rather than Unestra membership management, please contact Unestra Support so they can point you to the right resource -- I don't have verified detail on UnionFlow's own feature set.",
  },
  {
    id: "hoa-properties-residents",
    title: "HOA properties and residents",
    href: "/hoa/properties",
    category: "hoa",
    vertical: "HOA",
    audience: "HOA board members and property managers",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["property", "resident", "homeowner", "hoa member", "owner occupant"],
    text: "HOA organizations track properties and the residents linked to each one (owner-occupant, co-owner, non-resident owner, or tenant). Each resident is also a full member record for dues/assessments purposes.",
  },
  {
    id: "hoa-violations",
    title: "HOA violations",
    href: "/hoa/violations",
    category: "hoa",
    vertical: "HOA",
    audience: "HOA board members and property managers",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["violation", "compliance", "hoa rules", "notice"],
    text: "The Violations workflow lets HOA officers record a compliance issue against a property, notify residents, track a cure-by deadline, and resolve or dismiss the violation, with an audit trail of status changes.",
  },
  {
    id: "hoa-architectural-requests",
    title: "HOA architectural requests",
    href: "/hoa/architectural-requests",
    category: "hoa",
    vertical: "HOA",
    audience: "HOA board members, property managers, and owners",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "in_app",
    owner: "product",
    keywords: ["architectural request", "arc", "exterior modification", "property modification"],
    text: "Owners, co-owners, and non-resident owners can submit an Architectural Request for board review when they want to make an exterior or property modification. Officers with review or decide permission can move a request through review, approve (with or without conditions), deny, or request changes, with the decision visible to the resident who submitted it.",
  },
  {
    id: "support-contact",
    title: "Contacting Unestra Support",
    href: "mailto:support@getunestra.com",
    category: "general",
    vertical: "ALL",
    audience: "Anyone",
    publicationStatus: "published",
    version: "1",
    lastReviewedDate: "2026-08-05",
    visibility: "both",
    owner: "product",
    keywords: ["support", "contact", "help", "talk to a person", "customer service"],
    text: "For anything this assistant can't answer confidently, or for account-specific help, contact Unestra Support at support@getunestra.com.",
  },
];
