/**
 * Meeting Intelligence MVP — stable, machine-readable error codes used
 * across upload validation, the provider adapter, the background worker,
 * and minutes generation. Every code maps to a fixed HTTP status and a
 * "retryable" flag so the UI/worker never has to guess.
 */
export const MEETING_INTELLIGENCE_ERROR_CODES = [
  "MEETING_INTELLIGENCE_NOT_ENABLED",
  "MEETING_INTELLIGENCE_FILE_UNSUPPORTED",
  "MEETING_INTELLIGENCE_FILE_TOO_LARGE",
  "MEETING_INTELLIGENCE_UPLOAD_NOT_FOUND",
  "MEETING_INTELLIGENCE_UPLOAD_EXPIRED",
  "MEETING_INTELLIGENCE_STORAGE_OBJECT_MISSING",
  "MEETING_INTELLIGENCE_PROVIDER_UNAVAILABLE",
  // Distinct from PROVIDER_UNAVAILABLE (transient vendor-side outage, worth
  // retrying) — this is a permanent operator misconfiguration (missing/invalid
  // env var) that a retry can never fix. Deliberately NOT in RETRYABLE_CODES,
  // so the job-detail page never shows a "Retry" button that can only fail
  // again the same way. See config.ts.
  "MEETING_INTELLIGENCE_PROVIDER_MISCONFIGURED",
  "MEETING_INTELLIGENCE_PROVIDER_RATE_LIMITED",
  "MEETING_INTELLIGENCE_PROVIDER_TIMEOUT",
  "MEETING_INTELLIGENCE_INVALID_PROVIDER_RESPONSE",
  "MEETING_INTELLIGENCE_TRANSCRIPTION_FAILED",
  "MEETING_INTELLIGENCE_GENERATION_FAILED",
  "MEETING_INTELLIGENCE_JOB_NOT_FOUND",
  "MEETING_INTELLIGENCE_JOB_CANCELLED",
  "MEETING_INTELLIGENCE_INVALID_TRANSITION",
  "MEETING_INTELLIGENCE_ENROLLMENT_DISABLED",
  "MEETING_INTELLIGENCE_PERMISSION_DENIED",
  "MEETING_INTELLIGENCE_ORGANIZATION_ARCHIVED",
  "MEETING_INTELLIGENCE_CONSENT_REQUIRED",
  "MEETING_INTELLIGENCE_DRAFT_NOT_EDITABLE",
  "MEETING_INTELLIGENCE_EXPORT_NOT_APPROVED",
  // Pilot-readiness additions (see feedback.ts) — neither is retryable, both
  // are operator/input errors, not transient failures.
  "MEETING_INTELLIGENCE_FEEDBACK_INVALID",
  "MEETING_INTELLIGENCE_FEEDBACK_NOT_ELIGIBLE",
] as const;

export type MeetingIntelligenceErrorCode = (typeof MEETING_INTELLIGENCE_ERROR_CODES)[number];

const RETRYABLE_CODES: ReadonlySet<MeetingIntelligenceErrorCode> = new Set([
  "MEETING_INTELLIGENCE_PROVIDER_UNAVAILABLE",
  "MEETING_INTELLIGENCE_PROVIDER_RATE_LIMITED",
  "MEETING_INTELLIGENCE_PROVIDER_TIMEOUT",
  "MEETING_INTELLIGENCE_TRANSCRIPTION_FAILED",
  "MEETING_INTELLIGENCE_GENERATION_FAILED",
]);

const STATUS_FOR_CODE: Record<MeetingIntelligenceErrorCode, number> = {
  MEETING_INTELLIGENCE_NOT_ENABLED: 403,
  MEETING_INTELLIGENCE_FILE_UNSUPPORTED: 400,
  MEETING_INTELLIGENCE_FILE_TOO_LARGE: 400,
  MEETING_INTELLIGENCE_UPLOAD_NOT_FOUND: 404,
  MEETING_INTELLIGENCE_UPLOAD_EXPIRED: 400,
  MEETING_INTELLIGENCE_STORAGE_OBJECT_MISSING: 404,
  MEETING_INTELLIGENCE_PROVIDER_UNAVAILABLE: 502,
  MEETING_INTELLIGENCE_PROVIDER_MISCONFIGURED: 500,
  MEETING_INTELLIGENCE_PROVIDER_RATE_LIMITED: 429,
  MEETING_INTELLIGENCE_PROVIDER_TIMEOUT: 504,
  MEETING_INTELLIGENCE_INVALID_PROVIDER_RESPONSE: 502,
  MEETING_INTELLIGENCE_TRANSCRIPTION_FAILED: 502,
  MEETING_INTELLIGENCE_GENERATION_FAILED: 502,
  MEETING_INTELLIGENCE_JOB_NOT_FOUND: 404,
  MEETING_INTELLIGENCE_JOB_CANCELLED: 409,
  MEETING_INTELLIGENCE_INVALID_TRANSITION: 409,
  MEETING_INTELLIGENCE_ENROLLMENT_DISABLED: 403,
  MEETING_INTELLIGENCE_PERMISSION_DENIED: 403,
  MEETING_INTELLIGENCE_ORGANIZATION_ARCHIVED: 403,
  MEETING_INTELLIGENCE_CONSENT_REQUIRED: 400,
  MEETING_INTELLIGENCE_DRAFT_NOT_EDITABLE: 409,
  MEETING_INTELLIGENCE_EXPORT_NOT_APPROVED: 403,
  MEETING_INTELLIGENCE_FEEDBACK_INVALID: 400,
  MEETING_INTELLIGENCE_FEEDBACK_NOT_ELIGIBLE: 409,
};

export class MeetingIntelligenceError extends Error {
  readonly code: MeetingIntelligenceErrorCode;
  readonly status: number;
  readonly retryable: boolean;

  constructor(code: MeetingIntelligenceErrorCode, message: string) {
    super(message);
    this.name = "MeetingIntelligenceError";
    this.code = code;
    this.status = STATUS_FOR_CODE[code];
    this.retryable = RETRYABLE_CODES.has(code);
  }
}
