/**
 * Meeting Intelligence Technical Spike — privacy foundations.
 *
 * No customer recordings, no real PHI, and no production audio has ever
 * touched this module — every "meeting" referenced in this spike's tests
 * and mock UI is synthetic fixture data (see providers/mock-fixtures.ts).
 */

export const EXPERIMENTAL_FEATURE_NOTICE =
  "Meeting Intelligence is an internal technical prototype, not a released feature. It is visible only to APH Technologies for architecture validation.";

export const AI_OUTPUT_DISCLAIMER =
  "Content on this page was generated by an automated transcript and AI drafting process. It is not an official record until reviewed and approved by an authorized person.";

export const RECORDING_NOTICE_TEXT =
  "This meeting may be recorded and processed by an AI transcription service to produce draft minutes. Recording begins only after an organizer explicitly starts it, and participants should be informed before it begins.";

/** Raw audio is deleted this many days after processing completes — recordings are never retained permanently by default (see storage architecture in docs/meeting-intelligence-spike.md). */
export const DEFAULT_RECORDING_RETENTION_DAYS = 30;

/** Transcripts and generated minutes (text, much smaller and lower-risk than raw audio) may be retained longer, in line with typical meeting-minutes recordkeeping norms — organization-configurable in a production implementation. */
export const DEFAULT_TRANSCRIPT_RETENTION_DAYS = 365;

export interface MeetingIntelligenceSubmission {
  /** The organizer explicitly triggered recording/upload — never started by a background process or another user's action. */
  explicitUserTriggered: boolean;
  /** Participants were shown/told about the recording before it started. */
  recordingNoticeAcknowledged: boolean;
  /** The organization has confirmed it owns/has the right to submit this content — this framework never asserts an ownership claim itself. */
  organizationOwnershipConfirmed: boolean;
}

export interface PrivacyValidationResult {
  allowed: boolean;
  reason?: string;
}

/**
 * A minimal gate a real submission endpoint would run before accepting a
 * recording for processing — proves the shape of the check, not a
 * complete compliance implementation. All three conditions must be
 * explicitly true; none default to true, so a caller that forgets to ask
 * for consent fails closed rather than silently proceeding.
 */
export function validateMeetingIntelligenceSubmission(submission: MeetingIntelligenceSubmission): PrivacyValidationResult {
  if (!submission.explicitUserTriggered) {
    return { allowed: false, reason: "Recording/upload must be explicitly triggered by an organizer, not automated." };
  }
  if (!submission.recordingNoticeAcknowledged) {
    return { allowed: false, reason: "Participants must be notified of recording before processing begins." };
  }
  if (!submission.organizationOwnershipConfirmed) {
    return { allowed: false, reason: "The organization must confirm ownership of the submitted content." };
  }
  return { allowed: true };
}

export interface PrivacyChecklistItem {
  topic: string;
  status: "documented" | "prototyped" | "not_built";
  detail: string;
}

/** The privacy review checklist as structured data — see docs/meeting-intelligence-spike.md for the prose version and full sourcing. */
export const PRIVACY_CHECKLIST: PrivacyChecklistItem[] = [
  { topic: "Consent", status: "prototyped", detail: "validateMeetingIntelligenceSubmission() requires explicit trigger + notice acknowledgement before any processing." },
  { topic: "Recording notices", status: "prototyped", detail: "RECORDING_NOTICE_TEXT — must be shown to participants before recording starts." },
  { topic: "Retention", status: "documented", detail: `Raw audio: ${DEFAULT_RECORDING_RETENTION_DAYS} days. Transcripts/minutes: ${DEFAULT_TRANSCRIPT_RETENTION_DAYS} days, org-configurable in production.` },
  { topic: "Deletion", status: "documented", detail: "Automatic deletion job after retention window; manual delete-on-request must be supported before production launch." },
  { topic: "Encryption", status: "documented", detail: "TLS in transit (all provider APIs, uploads, signed URLs); at rest via DigitalOcean Spaces server-side encryption, matching the platform's existing Postgres-at-rest posture." },
  { topic: "Audit trail", status: "prototyped", detail: "Enrollment changes already audited via the Labs framework (docs/unestra-labs.md); per-job processing audit events are a production-implementation task, not built in this spike." },
  { topic: "Access logging", status: "not_built", detail: "Who viewed a transcript/recording — deferred to production; not needed to validate this spike's architecture." },
  { topic: "Transcript editing", status: "documented", detail: "Secretary Review stage must support editing the draft before approval — the workflow state machine models this stage but this spike doesn't build an editor UI." },
  { topic: "Human approval", status: "prototyped", detail: "generateDraftMinutes() output.status is hard-coded 'draft' with no code path to change it — approval must happen outside this module." },
  { topic: "AI disclaimer", status: "prototyped", detail: "AI_OUTPUT_DISCLAIMER attached to every generated DraftMinutes object." },
  { topic: "Organization ownership", status: "prototyped", detail: "validateMeetingIntelligenceSubmission() requires explicit ownership confirmation before accepting a submission." },
  { topic: "Data portability", status: "documented", detail: "Export as JSON/PDF via the same exporters already built for reports (docs/entitlements.md's pdfExport enforcement) — no new export mechanism needed in production." },
];
