const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  invoke: (channel, data) => ipcRenderer.invoke(channel, data),
});

contextBridge.exposeInMainWorld('civicflow', {
  license: {
    getStatus: () => ipcRenderer.invoke('license:getStatus'),
    activate: (data) => ipcRenderer.invoke('license:activate', data),
    canActivate: () => ipcRenderer.invoke('license:can-activate'),
    deactivate: (data) => ipcRenderer.invoke('license:deactivate', data),
    refresh: () => ipcRenderer.invoke('license:refresh'),
    status: () => ipcRenderer.invoke('license:getStatus'),
  },
  getDeviceId: () => ipcRenderer.invoke('get-device-id'),
  members: {
    list: (filters) => ipcRenderer.invoke('db:members:list', filters),
    get: (id) => ipcRenderer.invoke('db:members:get', id),
    create: (member) => ipcRenderer.invoke('db:members:create', member),
    update: (id, member) => ipcRenderer.invoke('db:members:update', id, member),
    archive: (id) => ipcRenderer.invoke('db:members:archive', id),
    restore: (id) => ipcRenderer.invoke('db:members:restore', id),
    deletePermanent: (id) => ipcRenderer.invoke('db:members:deletePermanent', id),
  },
  categories: {
    list: () => ipcRenderer.invoke('db:categories:list'),
    create: (data) => ipcRenderer.invoke('db:categories:create', data),
    update: (id, updates) => ipcRenderer.invoke('db:categories:update', id, updates),
  },
  organization: {
    get: () => ipcRenderer.invoke('organization:get'),
    set: (data) => ipcRenderer.invoke('organization:set', data),
    uploadLogo: (base64OrPath) => ipcRenderer.invoke('organization:upload-logo', base64OrPath),
    getSetupStatus: () => ipcRenderer.invoke('organization:getSetupStatus'),
    getSettings: () => ipcRenderer.invoke('organization:getSettings'),
    updateSettings: (data) => ipcRenderer.invoke('organization:updateSettings', data),
    completeSetup: () => ipcRenderer.invoke('organization:completeSetup'),
  },
  payments: {
    connectStripe: (orgId, orgEmail) => ipcRenderer.invoke('payments:connectStripe', orgId, orgEmail),
    createCheckoutSession: (data) => ipcRenderer.invoke('payments:createCheckoutSession', data),
    createCheckout: (data) => ipcRenderer.invoke('payments:createCheckout', data),
    createSubscription: (data) => ipcRenderer.invoke('payments:createSubscription', data),
    createExternalPayment: (data) => ipcRenderer.invoke('payments:createExternalPayment', data),
    syncFromCloud: () => ipcRenderer.invoke('payments:syncFromCloud'),
    listPendingExternal: () => ipcRenderer.invoke('payments:listPendingExternal'),
    approveExternal: (id) => ipcRenderer.invoke('payments:approveExternal', id),
    rejectExternal: (id) => ipcRenderer.invoke('payments:rejectExternal', id),
  },
  autopay: {
    pause: (data) => ipcRenderer.invoke('autopay:pause', data),
    resume: (data) => ipcRenderer.invoke('autopay:resume', data),
    cancelEnd: (data) => ipcRenderer.invoke('autopay:cancel_end', data),
    cancelNow: (data) => ipcRenderer.invoke('autopay:cancel_now', data),
  },
  getMemberDuesStatus: (memberId) => ipcRenderer.invoke('get-member-dues-status', memberId),
  events: {
    list: () => ipcRenderer.invoke('db:events:list'),
    listActive: () => ipcRenderer.invoke('db:events:listActive'),
    get: (id) => ipcRenderer.invoke('db:events:get', id),
    getDetails: (id) => ipcRenderer.invoke('get-event-details', id),
    create: (event) => ipcRenderer.invoke('db:events:create', event),
    update: (id, updates) => ipcRenderer.invoke('db:events:update', id, updates),
    archive: (id) => ipcRenderer.invoke('db:events:archive', id),
  },
  meetings: {
    list: () => ipcRenderer.invoke('db:meetings:list'),
    get: (id) => ipcRenderer.invoke('db:meetings:get', id),
    getSummary: (id) => ipcRenderer.invoke('db:meetings:getSummary', id),
    create: (meeting) => ipcRenderer.invoke('db:meetings:create', meeting),
    update: (id, updates) => ipcRenderer.invoke('db:meetings:update', id, updates),
    delete: (id) => ipcRenderer.invoke('db:meetings:delete', id),
  },
  attendance: {
    getForMeeting: (meetingId) => ipcRenderer.invoke('db:attendance:getForMeeting', meetingId),
    getAllMembersForMeeting: (meetingId) => ipcRenderer.invoke('db:attendance:getAllMembersForMeeting', meetingId),
    set: (meetingId, memberId, attended) => ipcRenderer.invoke('db:attendance:set', meetingId, memberId, attended),
    getForMember: (memberId) => ipcRenderer.invoke('db:attendance:getForMember', memberId),
  },
  campaigns: {
    list: () => ipcRenderer.invoke('db:campaigns:list'),
    listActive: () => ipcRenderer.invoke('db:campaigns:listActive'),
    getDetails: (id) => ipcRenderer.invoke('get-campaign-details', id),
    create: (campaign) => ipcRenderer.invoke('db:campaigns:create', campaign),
    update: (id, updates) => ipcRenderer.invoke('db:campaigns:update', id, updates),
    archive: (id) => ipcRenderer.invoke('db:campaigns:archive', id),
  },
  expenditures: {
    list: (filters) => ipcRenderer.invoke('expenditures:list', filters),
    create: (expenditure) => ipcRenderer.invoke('expenditures:create', expenditure),
    update: (id, updates) => ipcRenderer.invoke('expenditures:update', id, updates),
    delete: (id) => ipcRenderer.invoke('expenditures:delete', id),
    summary: (filters) => ipcRenderer.invoke('expenditures:summary', filters),
  },
  transactions: {
    list: (filters) => ipcRenderer.invoke('db:transactions:list', filters),
    create: (txn) => ipcRenderer.invoke('db:transactions:create', txn),
    update: (id, updates) => ipcRenderer.invoke('db:transactions:update', id, updates),
    delete: (id) => ipcRenderer.invoke('db:transactions:delete', id),
    addManualPayment: (data) => ipcRenderer.invoke('transaction:addManualPayment', data),
    getById: (id) => ipcRenderer.invoke('transaction:getById', id),
    updateById: (data) => ipcRenderer.invoke('transaction:update', data),
    importCsv: (rows) => ipcRenderer.invoke('transactions:importCSV', rows),
  },
  getDashboardStats: () => ipcRenderer.invoke('get-dashboard-stats'),
  getMemberDetails: (id) => ipcRenderer.invoke('get-member-details', id),
  updateMemberProfile: (id, updates) => ipcRenderer.invoke('update-member-profile', id, updates),
  export: {
    membersCsv: () => ipcRenderer.invoke('export:members-csv'),
    transactionsCsv: (filters) => ipcRenderer.invoke('export:transactions-csv', filters),
  },
  backup: {
    db: () => ipcRenderer.invoke('backup:db'),
  },
  restore: {
    db: () => ipcRenderer.invoke('restore:db'),
  },
  branding: {
    get: () => ipcRenderer.invoke('get-cbo-branding'),
    set: (data) => ipcRenderer.invoke('set-cbo-branding', data),
  },
  reports: {
    generatePeriodReport: (opts) => ipcRenderer.invoke('generate-period-report', opts),
    generateReceipt: (transactionId) => ipcRenderer.invoke('generate-receipt', transactionId),
    generateReceiptBuffer: (transactionId) => ipcRenderer.invoke('generate-receipt-buffer', transactionId),
    generateRosterActive: () => ipcRenderer.invoke('reports:roster-active-pdf'),
    exportRosterActiveCsv: () => ipcRenderer.invoke('reports:roster-active-csv'),
    generateRosterInactive: () => ipcRenderer.invoke('reports:roster-inactive-pdf'),
    exportRosterInactiveCsv: () => ipcRenderer.invoke('reports:roster-inactive-csv'),
    generateRosterCombined: () => ipcRenderer.invoke('reports:roster-combined-pdf'),
    exportRosterCombinedCsv: () => ipcRenderer.invoke('reports:roster-combined-csv'),
    generateMemberMonthly: (opts) => ipcRenderer.invoke('reports:member-monthly-pdf', opts),
    exportMemberMonthlyCsv: (opts) => ipcRenderer.invoke('reports:member-monthly-csv', opts),
    generateMemberContribution: (opts) => ipcRenderer.invoke('reports:member-contribution-pdf', opts),
    exportMemberContributionCsv: (opts) => ipcRenderer.invoke('reports:member-contribution-csv', opts),
    generateEventContribution: (opts) => ipcRenderer.invoke('reports:event-contribution-pdf', opts),
    exportEventContributionCsv: (opts) => ipcRenderer.invoke('reports:event-contribution-csv', opts),
    generateCampaignContribution: (opts) => ipcRenderer.invoke('reports:campaign-contribution-pdf', opts),
    exportCampaignContributionCsv: (opts) => ipcRenderer.invoke('reports:campaign-contribution-csv', opts),
    generateOrgFinancial: (opts) => ipcRenderer.invoke('reports:org-financial-pdf', opts),
    exportOrgFinancialCsv: (opts) => ipcRenderer.invoke('reports:org-financial-csv', opts),
    generateReportBuffer: (reportType, params) => ipcRenderer.invoke('reports:generateReportBuffer', { reportType, params }),
    getKpis: (filters) => ipcRenderer.invoke('reports:kpis', filters),
    getPaymentMethods: (orgId) => ipcRenderer.invoke('reports:getPaymentMethods', orgId),
    getTimeseries: (filters) => ipcRenderer.invoke('reports:timeseries', filters),
    getByType: (filters) => ipcRenderer.invoke('reports:by_type', filters),
    getByMember: (filters) => ipcRenderer.invoke('reports:by_member', filters),
    getRecent: (filters) => ipcRenderer.invoke('reports:recent', filters),
    exportCsv: (filters) => ipcRenderer.invoke('reports:exportCsv', filters),
    campaignSummary: (campaignId) => ipcRenderer.invoke('reports:campaign', campaignId),
    eventSummary: (eventId) => ipcRenderer.invoke('reports:event', eventId),
    campaignTopMembers: (campaignId) => ipcRenderer.invoke('reports:campaignTopMembers', campaignId),
  },
  receipt: {
    savePdfDialog: (transactionId) => ipcRenderer.invoke('receipt:save-pdf-dialog', transactionId),
    emailReceipt: (transactionId) => ipcRenderer.invoke('receipt:email-receipt', transactionId),
    isEmailConfigured: () => ipcRenderer.invoke('receipt:is-email-configured'),
  },
  admin: {
    deleteSampleData: () => ipcRenderer.invoke('admin:deleteSampleData'),
    getSampleDataCounts: () => ipcRenderer.invoke('admin:getSampleDataCounts'),
    listOrphanTransactions: (filters) => ipcRenderer.invoke('admin:listOrphanTransactions', filters),
    assignOrphanTransaction: (transactionId, memberId) => ipcRenderer.invoke('admin:assignOrphanTransaction', transactionId, memberId),
  },
  features: {
    getEnabled: () => ipcRenderer.invoke('features:getEnabled'),
    isEnabled: (feature) => ipcRenderer.invoke('features:isEnabled', feature),
  },
  grants: {
    list: (filters) => ipcRenderer.invoke('grants:list', filters),
    getById: (id) => ipcRenderer.invoke('grants:getById', id),
    create: (grant) => ipcRenderer.invoke('grants:create', grant),
    update: (id, updates) => ipcRenderer.invoke('grants:update', id, updates),
    archive: (id) => ipcRenderer.invoke('grants:archive', id),
    restore: (id) => ipcRenderer.invoke('grants:restore', id),
    deletePermanent: (id) => ipcRenderer.invoke('grants:deletePermanent', id),
    allocate: (allocation) => ipcRenderer.invoke('grants:allocate', allocation),
    summary: (organizationId) => ipcRenderer.invoke('grants:summary', organizationId),
  },
  grantReports: {
    listForGrant: (grantId) => ipcRenderer.invoke('grantReports:listForGrant', grantId),
    create: (report) => ipcRenderer.invoke('grantReports:create', report),
    update: (id, updates) => ipcRenderer.invoke('grantReports:update', id, updates),
    delete: (id) => ipcRenderer.invoke('grantReports:delete', id),
    markSubmitted: (id) => ipcRenderer.invoke('grantReports:markSubmitted', id),
  },
  // Membership lifecycle
  membership: {
    getCurrentStatus: (memberId) => ipcRenderer.invoke('membership:getCurrentStatus', memberId),
    listPeriods: (memberId) => ipcRenderer.invoke('membership:listPeriods', memberId),
    startNewPeriod: (memberId, startDate, reason) => ipcRenderer.invoke('membership:startNewPeriod', memberId, startDate, reason),
    setInactive: (memberId, reason) => ipcRenderer.invoke('membership:setInactive', memberId, reason),
    terminate: (memberId, endDate, reason) => ipcRenderer.invoke('membership:terminate', memberId, endDate, reason),
    reinstate: (memberId, mode, date, reason) => ipcRenderer.invoke('membership:reinstate', memberId, mode, date, reason),
  },
  // Financial ledger (immutable)
  financeTxns: {
    list: (memberId, includeVoided) => ipcRenderer.invoke('finance:txns:list', memberId, includeVoided),
    listAll: (filters) => ipcRenderer.invoke('finance:txns:listAll', filters),
    getById: (id) => ipcRenderer.invoke('finance:txns:getById', id),
    create: (data) => ipcRenderer.invoke('finance:txns:create', data),
    correct: (originalId, correctAmount, correctDate, reason) => ipcRenderer.invoke('finance:txns:correct', originalId, correctAmount, correctDate, reason),
    adjust: (originalId, deltaAmount, reason) => ipcRenderer.invoke('finance:txns:adjust', originalId, deltaAmount, reason),
    updateNotes: (id, notes) => ipcRenderer.invoke('finance:txns:updateNotes', id, notes),
    update: (id, updates) => ipcRenderer.invoke('finance:txns:update', id, updates),
    reverse: (id, reason, date) => ipcRenderer.invoke('finance:txns:reverse', id, reason, date),
    delete: (id, deletedBy) => ipcRenderer.invoke('finance:txns:delete', id, deletedBy),
  },
  // Email system
  email: {
    getSettings: () => ipcRenderer.invoke('email:settings:get'),
    updateSettings: (data) => ipcRenderer.invoke('email:settings:update', data),
    sendTest: (toEmail) => ipcRenderer.invoke('email:send:test', toEmail),
    queue: (data) => ipcRenderer.invoke('email:queue', data),
    processOutbox: () => ipcRenderer.invoke('email:processOutbox'),
    outboxList: (filters) => ipcRenderer.invoke('email:outbox:list', filters),
    resolveRecipients: (group) => ipcRenderer.invoke('email:resolveRecipients', group),
    sendReport: (data) => ipcRenderer.invoke('email:sendReport', data),
    sendReportToAllMembers: (data) => ipcRenderer.invoke('email:sendReportToAllMembers', data),
    sendDuesReminder: (member) => ipcRenderer.invoke('email:sendDuesReminder', member),
  },
  // Roles
  roles: {
    getCurrent: () => ipcRenderer.invoke('roles:getCurrent'),
    setCurrent: (role) => ipcRenderer.invoke('roles:setCurrent', role),
  },
  // Audit logs
  audit: {
    list: (filters) => ipcRenderer.invoke('audit:list', filters),
  },
  // Data Import
  dataImport: {
    templatesList: () => ipcRenderer.invoke('import:templates:list'),
    templatesDownload: (importType) => ipcRenderer.invoke('import:templates:download', { importType }),
    parseFile: (data) => ipcRenderer.invoke('import:file:parse', data),
    preview: (data) => ipcRenderer.invoke('import:preview', data),
    commit: (data) => ipcRenderer.invoke('import:commit', data),
    runsList: (filters) => ipcRenderer.invoke('import:runs:list', filters),
    runsGet: (id) => ipcRenderer.invoke('import:runs:get', id),
    // Legacy endpoints (if needed elsewhere)
    parseFileLegacy: (data) => ipcRenderer.invoke('import:parseFile', data),
    validateLegacy: (data) => ipcRenderer.invoke('import:validate', data),
    executeLegacy: (data) => ipcRenderer.invoke('import:execute', data),
    getTemplateLegacy: (importType) => ipcRenderer.invoke('import:getTemplate', importType),
  },
});
